require:
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'db/**/*.rb'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'bin/bundle'

Style/SignalException:
  Enabled: false

Naming/MethodName:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
